### PR TITLE
Psr 591 592 593

### PR DESCRIPTION
**Pull request by EricSiegNW**
Text changes from the 3 stories linked:

https://sagebionetworks.jira.com/browse/PSR-531
https://sagebionetworks.jira.com/browse/PSR-532
https://sagebionetworks.jira.com/browse/PSR-533

### CODE REVIEW

**Comment by dephillipsmichael** [comment]
@EricSiegNW can you describe how yo completed https://sagebionetworks.jira.com/browse/PSR-531 as well as provide a screenshot in the story before you mark it as resolved?

Can you also provide screenshots for https://sagebionetworks.jira.com/browse/PSR-532
https://sagebionetworks.jira.com/browse/PSR-533 in the jira issues.

**Comment by dephillipsmichael** [comment]
@EricSiegNW this doesn't seem correct.  You are changing copy for all of these tasks which is not what is being requested in the Jira issue. You need to only change the copy for the Symptom History task.

**Comment by EricSiegNW** [comment]
> @EricSiegNW can you describe how yo completed https://sagebionetworks.jira.com/browse/PSR-531 as well as provide a screenshot in the story before you mark it as resolved?


Marked it as resolved as the code was already merged in last week when pulled from my branch. Screenshot added.

**Comment by dephillipsmichael** [comment]
> > @EricSiegNW can you describe how yo completed https://sagebionetworks.jira.com/browse/PSR-531 as well as provide a screenshot in the story before you mark it as resolved?
> 
> Marked it as resolved as the code was already merged in last week when pulled from my branch. Screenshot added.

I'm confused, if it was merged in last week, why is it listed in this PR?

**Pull request closed without merging**
