### PR TITLE
Participant file upload

### PR DESCRIPTION
**Pull request by Erin-Mounts**

### CODE REVIEW

**Comment by dephillipsmichael** [comment]
Getting some compile errors when trying to test

Screen Shot 2021-07-22 at 9 11 13 PM

**Comment by dephillipsmichael** [comment]
@Erin-Mounts tagging you in case you didn't see my screenshot

**Comment by Erin-Mounts** [comment]
What Xcode version are you using? It builds fine for me in 12.5.1 (12E507). Also, I have Build System set as New Build System in Workspace Settings, both for Shared and Per-User settings.

**Comment by dephillipsmichael** [comment]
> What Xcode version are you using? It builds fine for me in 12.5.1 (12E507). Also, I have Build System set as New Build System in Workspace Settings, both for Shared and Per-User settings.

It's probably your compiler in 12.5.1, I'm running 12.3.  

The pattern you are using that is causing the errors seems odd to me. You shouldn't be able to create a new variable with the same name as the old one from within a function, and just to prove it isn't nil.  Why don't you rename it **contentLengthStringUnwrapped**, or why don't you do **guard contentLengthString != nil** instead?

**Comment by Erin-Mounts** [comment]
It's a common pattern, used all over the place in Psorcast and its libraries, including several other places in the ParticipantFileManager code (do a global find for this regex: 'guard let (.*) = \1 ' without the single quotes), to check and bail out if a variable is nil, and if it's not nil, to be able to treat it as non-optional for the remainder of the context so you don't have to keep using ! every time. The fact that v12.3 of Xcode's compiler only complains about that one usage implies it must be a bug in that version of the compiler.

**Comment by dephillipsmichael** [comment]
> It's a common pattern, used all over the place in Psorcast and its libraries, including several other places in the ParticipantFileManager code (do a global find for this regex: 'guard let (.*) = \1 ' without the single quotes), to check and bail out if a variable is nil, and if it's not nil, to be able to treat it as non-optional for the remainder of the context so you don't have to keep using ! every time. The fact that v12.3 of Xcode's compiler only complains about that one usage implies it must be a bug in that version of the compiler.

I'm not sure we are on the same page here.  It seems like you think I'm talking about your use of conditional binding in general, instead of this particular use case of it.  The compiler error is pretty straightforward and is an accurate description of what you're doing.

You're defining a let constant, and then re-defining it in the same function:

let contentLengthString = "value"
guard let contentLengthString = "new value" else { return }

**Comment by Erin-Mounts** [comment]
Is your compiler also complaining about the other uses of that pattern in the same file, i.e. lines 456 and 457, and again at lines 462 and 463? If so, it may be that the language rules have been changed to allow this in the newer version. In any case, this pattern of "guard let xxx = xxx " where xxx has a previous definition has long been used to validate and "de-optionalize" function parameters and instance vars within the body of a method (e.g. see lines 442 and 482).

**Comment by dephillipsmichael** [comment]
> Is your compiler also complaining about the other uses of that pattern in the same file, i.e. lines 456 and 457, and again at lines 462 and 463? If so, it may be that the language rules have been changed to allow this in the newer version. In any case, this pattern of "guard let xxx = xxx " where xxx has a previous definition has long been used to validate and "de-optionalize" function parameters and instance vars within the body of a method (e.g. see lines 442 and 482).

Yeah, it complained about all your uses of it.  I may be wrong, but I don't think any language I know of allows you to define a const variable twice in the same scope, so I'm not sure how you have been getting away with it.  

Anyways, seems like it's really not important to continue the discussion, so I just went and fixed it myself and pushed.

**Comment by dephillipsmichael** [comment]
I have other priorities right now, but I should be able to take a deeper look at this Friday.

**Comment by dephillipsmichael** [comment]
Working well for me.  Upload takes over 20 seconds for a PNG, but compressing properly to JPEG to ~1.0 mb is much quicker, < 5 seconds.  Download was similar and is quick when JPEG.


https://user-images.githubusercontent.com/5590748/127926119-fe7f531c-e01c-46ff-9cff-982b8a0daf60.mov

**Comment by dephillipsmichael** [comment]
@Erin-Mounts you can merge in the Bridge-iOS-SDK changes new and version, and I can look at pointing Psorcast at the new version.

**Review by DanWebster — APPROVED** [review]

**Comment by DanWebster** [comment]
@dephillipsmichael I will defer to you on when this is ready to merge

**Comment by dephillipsmichael** [comment]
@Erin-Mounts this seems ready to go, do you think we need to update carthage?

**Comment by Erin-Mounts** [comment]
@dephillipsmichael it might work without changing carthage, but ideally you should prolly add this to the Psorcast-iOS cartfile:

github "Sage-Bionetworks/Bridge-iOS-SDK" ~> 4.4.84

**Comment by dephillipsmichael** [comment]
I made that change and it worked great, thanks.

**Comment by dephillipsmichael** [comment]
@Erin-Mounts merging it in.  Once again, great job on this feature, and appreciate the level of detail and testing you put into it.

**Comment by DanWebster** [comment]
> @Erin-Mounts merging it in. Once again, great job on this feature, and appreciate the level of detail and testing you put into it.

@Erin-Mounts echoing this sentiment from MDP; great to have this feature implemented and tested.  Now let's get it battle-tested in real world conditions!

**Pull request merged**
