### PR TITLE
SMS Sign In Bug Fixes

### PR DESCRIPTION
**Pull request by dephillipsmichael**
Various fixes to support a single sign up / sign in flow.  This is now working for both new/existing phone-number based accounts and only receives a single sms code each request.

### CODE REVIEW

**Review by DanWebster — CHANGES_REQUESTED** [review]
@dephillipsmichael, I am not getting the text message, with the console output showing as:

2021-02-26 13:26:24.577394-0800 Psorcast[51514:7313926] Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
2021-02-26 13:26:24.589163-0800 Psorcast[51514:7313926] Could not signal service com.apple.WebKit.Networking: 113: Could not find specified service
2021-02-26 13:26:35.678467-0800 Psorcast[51514:7313926] Prepared request--URL:
https://webservices.sagebridge.org/v3/auth/phone
Headers:
{
    "Accept-Language" = "en-US";
    "Cache-Control" = "no-cache";
    "Content-Type" = "application/json; charset=utf-8";
    "User-Agent" = "Psorcast/8 (iPhone X; iOS/14.4) BridgeSDK/75";
}
Body:
{"study":"sage-psorcast","phone":{"type":"Phone","number":"6507994304","regionCode":"US"}}
2021-02-26 13:27:36.333039-0800 Psorcast[51514:7315049] [tcp] tcp_input [C1.1:3] flags=[R] seq=2134637381, ack=0, win=0 state=LAST_ACK rcv_nxt=2134637381, snd_una=899349133

**Comment by dephillipsmichael** [comment]
> @dephillipsmichael, I am not getting the text message, with the console output showing as:
> 
> 2021-02-26 13:26:24.577394-0800 Psorcast[51514:7313926] Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
> 2021-02-26 13:26:24.589163-0800 Psorcast[51514:7313926] Could not signal service com.apple.WebKit.Networking: 113: Could not find specified service
> 2021-02-26 13:26:35.678467-0800 Psorcast[51514:7313926] Prepared request--URL:
> https://webservices.sagebridge.org/v3/auth/phone
> Headers:
> {
> "Accept-Language" = "en-US";
> "Cache-Control" = "no-cache";
> "Content-Type" = "application/json; charset=utf-8";
> "User-Agent" = "Psorcast/8 (iPhone X; iOS/14.4) BridgeSDK/75";
> }
> Body:
> {"study":"sage-psorcast","phone":{"type":"Phone","number":"6507994304","regionCode":"US"}}
> 2021-02-26 13:27:36.333039-0800 Psorcast[51514:7315049] [tcp] tcp_input [C1.1:3] flags=[R] seq=2134637381, ack=0, win=0 state=LAST_ACK rcv_nxt=2134637381, snd_una=899349133

My fault Dan, I left in some old code that was making it into some user flows. I fixed it and you should be good to go now.

**Comment by DanWebster** [comment]
@dephillipsmichael The pathway when I don't exist already is perfect.  I get the code, I enter it, we're on our way.

When I already have an existing account, the SMS never gets sent, unfortunately.  There did not seem to be anything particularly useful in the logs as I was doing this.  When I was waiting for an SMS, but then I deleted my account on Bridge Study Manager, then tapped 're-send the link', then it worked.

So it seems like there is something going on to check whether or not an account with that phone number exists, but I didn't get an error message back in response that I could see, just saw the following seemingly standard Bridge call: 

2021-02-27 12:56:18.093604-0800 Psorcast[55549:7573880] Prepared request--URL:
https://webservices.sagebridge.org/v3/auth/signUp
Headers:
{
    "Accept-Language" = "en-US";
    "Cache-Control" = "no-cache";
    "Content-Type" = "application/json; charset=utf-8";
    "User-Agent" = "Psorcast/8 (iPhone X; iOS/14.4) BridgeSDK/75";
}
Body:
{"dataGroups":[],"phone":{"type":"Phone","number":"6507994304","regionCode":"US"},"checkForConsent":true,"type":"SignUp","attributes":{},"study":"sage-psorcast"}

Don't know if that is helpful for troubleshooting, but let me know if there is more info I can provide or if you want to troubleshoot with me synchronously (don't remember if you have an iPhone with sim -- if that matters)

**Comment by DanWebster** [comment]
Accepting and merging so that we can get the initial sign up working with people who don't have accounts created already ,and created a new story to troubleshoot the 'sign-in' function

**Pull request merged**
